### ISSUE TITLE
write filename for error

### ISSUE THREAD

**Issue by marwin1991** [logchange/logchange#277]
[ERROR] Cannot deserialize value of type `java.lang.Long` from Object value (token `JsonToken.START_OBJECT`)
[ERROR]  at [Source: (FileInputStream); line: 6, column: 5] (through reference chain: dev.logchange.core.format.yml.changelog.entry.YMLChangelogEntry["issues"]->java.util.ArrayList[0])
[ERROR] -> [Help 1]

**Comment by witx98** [comment]
I think it was solved in https://github.com/logchange/logchange/pull/318

**Comment by marwin1991** [comment]
@witx98 thanks! closing
