### ISSUE TITLE
Removing version suffixes with a “-” sign.

### ISSUE THREAD

**Issue by witx98** [logchange/logchange#321]
Is it really necessary to remove all version suffixes that start with the - sign?

https://github.com/logchange/logchange/blob/ac03624cf5b0d2f11dd2806f7bf497080bc6bfea/logchange-maven-plugin/src/main/java/dev/logchange/maven_plugin/mojo/release/ReleaseVersionMojo.java#L67-L70

I find it odd that it's currently impossible to release a changelog for versions with suffixes like `-RC` (release candidate). This limitation seems inconsistent, especially since the README of the Valhalla project (a tool commonly used in combination with logchange) clearly states that you should be able to release any type of version:

Valhalla README reference: [README.md#L92-L96](https://github.com/logchange/valhalla/blob/302dad883a8a85f5b04a4f2947a7e83b43a0a296/README.md?plain=1#L92-L96)

The only explanation I could find for this behavior was in [issue #35](https://github.com/logchange/logchange/issues/35), where it was mentioned that this change was introduced to remove `-SNAPSHOT` suffixes. Are there any other reasons or contraindications for not allowing other types of version suffixes?

@marwin1991

**Comment by marwin1991** [comment]
solved by #322
