### ISSUE TITLE
Aggregate dependency update entries

### ISSUE THREAD

**Issue by Riserax** [logchange/logchange#344]
It would be great if in generated/released version summary, instead of several version update entries for a particular dependency, there was only one aggregated one.

### Example
```
Zaktualizowano wersje ****************-mediator z 1.5.4 na 1.5.5 
Zaktualizowano wersje ****************-mediator z 1.5.5 na 1.6.0
Zaktualizowano wersje ****************-mediator z 1.6.0 na 1.6.1
Zaktualizowano wersje ****************-mediator z 1.6.1 na 1.6.2
Zaktualizowano wersje ****************-mediator z 1.6.2 na 1.6.3 
```

### Suggested solution
```
Zaktualizowano wersję ****************-mediator z 1.5.4 na 1.6.3
```
This would result in better readability of the entries.

**Comment by marwin1991** [comment]
@witx98 maybe we can tak about it ?

**Comment by witx98** [comment]
@marwin1991  We would probably need something like `dependency_update_template` in configuration:

```yml
dependency_update_template: "{UPDATE_LABEL} {DEPENDENCY_NAME} {FROM} {OLD_VERSION} {TO} {NEW_VERSION}"

**Comment by marwin1991** [comment]
@witx98 we would have to change this:

https://github.com/logchange/logchange/blob/main/add_entry.sh

or we can create something to create entry only about dependency update ?

I remember that it was hard to use maven plugin in renovate so thats why I have created bash script

**Comment by witx98** [comment]
What should we do if the last actual version isn’t the highest among all updates? For example, consider the following update sequence:

1.0.0 -> 1.0.1
1.0.1 -> 1.0.2
1.0.2 -> 1.0.1 (we downgrade the final version for some reason)
How should we determine the last actual version in such cases?

@marwin1991

**Comment by marwin1991** [comment]
maybe we just should do not change anything, because it's imposible.

cc @Riserax
